### ISSUE TITLE
Extensions

### ISSUE THREAD

**Issue by Martii** [mikeshiyan/broken_image_stylizer#1]
Please take a look at [What is a User Script?](https://openuserjs.org/about/Userscript-Beginners-HOWTO#what-is-a-user-script-) vs. [What is a Library Script?](https://openuserjs.org/about/Userscript-Beginners-HOWTO#what-is-a-library-script-) if you wish to enable auto-sync with GH to OUJS.

Thanks,
OUJS Admin

**Comment by mikeshiyan** [comment]
Thanks. I didn't know it matters @ OpenUserJS. For example, Greasy Fork syncs OK as is.
Gonna rename the script.

**Comment by Martii** [comment]
> Greasy Fork syncs OK as is.

That would be a bug on their site... See [GM](http://wiki.greasespot.net/Greasemonkey_Manual:Installing_Scripts#About_User_Scripts) and [GM Port](http://sourceforge.net/p/greasemonkey/wiki/Greasemonkey_Manual%3AInstalling_Scripts/#about-user-scripts) documentation.

> Gonna rename the script.

Good idea. :) Now someone can install directly from GH too since it conforms to the extension specification.

> OpenUserJS

Welcome aboard! :)
